sudo: required

language: csharp

mono: none

dotnet: 2.1.4

services:
  - docker

env:
  global:
  - secure: PGlJmDNH4WUDbnlhcY+tyxFKVM+Aw2XZGhUINuHW1tfjUFcWvDp7hATOW7pNHExPhP24Bm3vfRI6YH82T1S0koXz0MxMFK7YpJmb/x7vGTp5TTb+Ldb8dlIgvVJl6yZFVx0BXFJ303gp9h0FrwBTMPdjcdnXbNLuUiSG9IfUGLmw4Jbj8qhEUdGUpOK54LWyY+ZeLcfqBoGhRD3iRYgRkzVaj84TUA93MGrINaZ3vHWApMXyLj+yvljP1DCqfX3HdpR8MxlGr/yBuHJdZixb1IhxMFPO5EYzx0jJNc8DjLsTDjhQ2p8BisRVIUuczE1UBuWwAZGq3xav+biGqcZZnRHb5hmP98eKWZQBQXBLeYC1lINxLhpdoDh6/8FjVPpk7s4d1RyOVsyT8+o7C1UzBlDb6vejlAaLm8Qb3me6OMv8R4cbCE5UvFqmVUKaj7Jj65NGp8KpB23ES0iCKFyhBHdGtBpbMXC8MriCbyd13lLK/w63Z7bDuZrTQT1xmnFD977rIwvproy0tD1GwVr+DebzMvIyjvTwgfOxtyB4UEjfUCmdzq96GSdFRD2FfUQeMm3j9bAPLU8mKbcF0ReczNFGY2gi7VTql+dkE3aaceorVQTucsNuFuWAnjpWOD8cTKwlne+IlBQ/VXPn9e8CqEZ/aNgMsVbGwQMeNuP+P9M=
  - secure: mvpkBqjf/FE0WVeMlSbTLTFe9XsqoQb/maeGJJIxyuVHaf9Jq/zTZfebgCe8mMIHlGCy3vke5e3x3F1LGW9g5pfacCLKkHs5+rrvNVH7h9+0Q0tDipnoe5eJkvu2Nlcv72yjOHh8CI6vdHVRnPukDrYkJxFlodeQD8sn2NcCO7Jh2SN2jQfqk8Noy0aJr8WgKy+AHRTV6yvYsafiEsPztUFy1mQ0BnlS14NGL7J72ocq7pxDGB06BBJEgo7iu55IPqK2PCOGi8+4Ck8lHSG3Lk7JXmZKorsgLte71lLn6o631OAyvLBQqLsLedlFhxpIrxT5ZDVJOldmRT/BSRtNfq2I8vR4umZ436XoyWU5ZQXCpUNF85Fqneoj3HoHYPL18tdcTSxm/i9TKJvoeFSwvVm72SvrS+JYofCuRv1TVvWY9yksdI9VvlkZGVwV5ANQVkt1KM6n0A+eTL58fv2sVSHnEjQAr732k8MQLciEBj4R4fH6WX2QjO6YGnqTPZV4n1Fyx/fqWfp7yf59i2Jd+gncc46Y3xn97eqNpz/+CGBoDQQ5db3rwM2leDdc0obDDVEONSabAXWyK+BECj4BgG2PWiuxZM1iMGW8Ym7wKqdq/HHfAgyk5l4aQFgXZarp4GB48I4P+ZLJrm7yWSj/DMMMcFEOE3raQPIbDsfSkGM=

script:
  - dotnet test F1WM.UnitTests
  - docker build -t f1wm:latest . --build-arg connectionString='$ConnectionString'
