sudo: required

language: csharp

mono: none

dotnet: 2.1.4

services:
- docker

env:
  global:
  - secure: mvpkBqjf/FE0WVeMlSbTLTFe9XsqoQb/maeGJJIxyuVHaf9Jq/zTZfebgCe8mMIHlGCy3vke5e3x3F1LGW9g5pfacCLKkHs5+rrvNVH7h9+0Q0tDipnoe5eJkvu2Nlcv72yjOHh8CI6vdHVRnPukDrYkJxFlodeQD8sn2NcCO7Jh2SN2jQfqk8Noy0aJr8WgKy+AHRTV6yvYsafiEsPztUFy1mQ0BnlS14NGL7J72ocq7pxDGB06BBJEgo7iu55IPqK2PCOGi8+4Ck8lHSG3Lk7JXmZKorsgLte71lLn6o631OAyvLBQqLsLedlFhxpIrxT5ZDVJOldmRT/BSRtNfq2I8vR4umZ436XoyWU5ZQXCpUNF85Fqneoj3HoHYPL18tdcTSxm/i9TKJvoeFSwvVm72SvrS+JYofCuRv1TVvWY9yksdI9VvlkZGVwV5ANQVkt1KM6n0A+eTL58fv2sVSHnEjQAr732k8MQLciEBj4R4fH6WX2QjO6YGnqTPZV4n1Fyx/fqWfp7yf59i2Jd+gncc46Y3xn97eqNpz/+CGBoDQQ5db3rwM2leDdc0obDDVEONSabAXWyK+BECj4BgG2PWiuxZM1iMGW8Ym7wKqdq/HHfAgyk5l4aQFgXZarp4GB48I4P+ZLJrm7yWSj/DMMMcFEOE3raQPIbDsfSkGM=
  - secure: TnNlGS4GzaVjykNjWWMriA6ehD3jwwEvxlqEzuGIWCxjOogUqNsyfEIc71qL/L4DXWKKMbS0GuFTVgL8pJ9KLAF168Qb/w6QyfTJ7RUgcHWabFZ+7AZrwWqbsqFUXd2S1B1ev3b5t6Gs1zd9SwiJxKa4QDYlu4bkUr8YNe4balRafFbE5HhEVZ73AB4W1jNQ+3CRo7E0V0WvkufQ+cZPa0ZWfVdDhTXcwqHHIm+ySQLHVBopTSaQVWK2Pejqq/3R+o0P5I7S7ZqnFapHExx1EaAvfPETbZ2fWwXIgD2HaPx9oRTNz1K3SqKgn6fKtmGgyz9I5S6dC8hJne4XWEcsWkF0ztN4z7iQuSC2h1U23bx50tDrQyGOZ1OYtc3IcVVr1rgPeuAm/vmz9IQt2cWlwUvAr6tmYFhJ/uBlexiFbNRA3Ce7gv0eg7uj4eNESQo9XN3VQ4UXRIgUmuj/DPawgjq0CQAyuL9dlKuozK2DSWZryAAHfUd4+mKF0YYQBK9m1jqDQg8O1HPssvORw/Lg5pZwkc161Jh277+Ju3mdH4Z3MfwhLOkakTRuYBpJRVxJFV3nakHopgwfJCMh3E6U/A4b3S7EYin2vKNACMK8rKK1SjtxVWFvMDFtXfW8cgfuyLLN9abgrFZ3MazDBDbarSdrRYcDl7rCo+ESMgkzeVE=
script:
- dotnet test F1WM.UnitTests
- docker build -t f1wm:latest . --build-arg connectionString='$ConnectionString'
