sudo: required

language: csharp

mono: none

dotnet: 2.1.4

services:
- docker

env:
  global:
  - secure: mvpkBqjf/FE0WVeMlSbTLTFe9XsqoQb/maeGJJIxyuVHaf9Jq/zTZfebgCe8mMIHlGCy3vke5e3x3F1LGW9g5pfacCLKkHs5+rrvNVH7h9+0Q0tDipnoe5eJkvu2Nlcv72yjOHh8CI6vdHVRnPukDrYkJxFlodeQD8sn2NcCO7Jh2SN2jQfqk8Noy0aJr8WgKy+AHRTV6yvYsafiEsPztUFy1mQ0BnlS14NGL7J72ocq7pxDGB06BBJEgo7iu55IPqK2PCOGi8+4Ck8lHSG3Lk7JXmZKorsgLte71lLn6o631OAyvLBQqLsLedlFhxpIrxT5ZDVJOldmRT/BSRtNfq2I8vR4umZ436XoyWU5ZQXCpUNF85Fqneoj3HoHYPL18tdcTSxm/i9TKJvoeFSwvVm72SvrS+JYofCuRv1TVvWY9yksdI9VvlkZGVwV5ANQVkt1KM6n0A+eTL58fv2sVSHnEjQAr732k8MQLciEBj4R4fH6WX2QjO6YGnqTPZV4n1Fyx/fqWfp7yf59i2Jd+gncc46Y3xn97eqNpz/+CGBoDQQ5db3rwM2leDdc0obDDVEONSabAXWyK+BECj4BgG2PWiuxZM1iMGW8Ym7wKqdq/HHfAgyk5l4aQFgXZarp4GB48I4P+ZLJrm7yWSj/DMMMcFEOE3raQPIbDsfSkGM=
  - secure: DLRSUbXestGnWcmk8vLgEHLJQVCBFAD0PYYv32nTpFejaORLZjvdIiyGICeamkhscIfR8psXjDVR2qVaG+W6mmcILTCwdLlxzvVrN2p5Zbcc6j1o11URpi0Z+51MoMgkM6JgPBncax9oMjat8gVGvQiq1xh4hVfcj2lVudSEKpzxrt83QHxQb1wySWKY/o2V34j6ZIo0UE63ZxsWrRy1bqPwigg0LvabtgoOY9E5HKDPNO1kQGRA6mZSuoR9hNzQFnCWk3virMW+E74/OLyOxzP8m2Wt7dkpTRjNrkoePNMyLiqBPqWChUdsVDt/uQEapLbXATP+6QdEUGbIw+/xc3ldRt7jtFXoQxLUbzoOmaiow6EOAT2jGJKMv3nZN92cSPdl+u81yWtrZxXeSOBKOH6i2uVOiPWsO8qtogvyMgl87Mu6vjSFgq/yNqMV6slr2dlViQDMFCqch/bgoVQKUBU0TUW+3oMwv522tEugycC7oHI8kQMQZwCGPnRxqZJokReoEq8gdWMjJRR/2Mz//4pUTH0F3OCx0V2NVmGbJ8iZyvDNREKXZetIZyRBy098etyxNXVcU2xmmHx+OOAwYw/C33oF4T7N2GcLmZnjhh+OG5SfvlV2YYAftIwjRZetQ7RUmm7aNIkfh5/f9/zomdQ1iky56DwlcGBSTYFPdlk=
script:
- docker build -t f1wm:latest . --build-arg connectionString='$ConnectionString'
- docker save f1wm:latest | bzip2 | ssh $DeployServer 'bunzip2 | docker load && docker stop f1wm_webapi || true && docker rm f1wm_webapi || true && docker run --restart=always --name f1wm_webapi -d -p 80:80 f1wm:latest'
