version: "3"

services:
  app:
    build:
      context: F1WM
      dockerfile: Dockerfile
    expose:
      - "5000"
    
  proxy:
    build:
      context: F1WM.Proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app